version: "2.1"

networks:
  test:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
    depends_on:
      - db
    networks:
      - test

  db:
    image: opavlova/db-mysql:5.7-test
    container_name: db
    ports:
      - "13306:3306"
    networks:
      - test
